import fs from "node:fs";
import path from "node:path";

export interface InitCommandOptions {
  force?: boolean;
  preCommit?: boolean;
  githubAction?: boolean;
}

const DEFAULT_CONFIG = `version: "1"

policy:
  failOn: high

ignore:
  paths:
    - "examples/**"
`;

const DEFAULT_IGNORE = `# Intentionally insecure examples and documentation examples
examples/**
docs/examples/**

# Fixture directories and fixture-like files
**/fixtures/**
**/__fixtures__/**
**/*.fixture.*
**/*.fixtures.*

# Generated dependency, build, and coverage artifacts
node_modules/**
dist/**
packages/*/dist/**
package-lock.json
pnpm-lock.yaml
yarn.lock
coverage/**
packages/*/coverage/**

**/*.test.ts
**/*.spec.ts
`;

const DEFAULT_GITHUB_ACTION = `name: GuardDiff Security Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  guarddiff:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      security-events: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run GuardDiff
        uses: guarddiff/guarddiff@v1
        with:
          fail-on: high
          post-comment: true
          sarif: true
          annotations: true
          rules-update-check: true
          sarif-file: guarddiff-results.sarif
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF to Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: guarddiff-results.sarif
`;

const DEFAULT_PRE_COMMIT_HOOKS = `- id: guarddiff
  name: GuardDiff Security Check
  description: AIが書いた危険な差分を、コミット前に止める
  language: node
  entry: guarddiff staged
  pass_filenames: false
  stages: [commit]
`;

const DEFAULT_PRE_COMMIT_HOOK = `#!/bin/sh
# GuardDiff pre-commit hook
# Generated by guarddiff init --pre-commit

if ! command -v guarddiff >/dev/null 2>&1; then
  echo "GuardDiff is not installed. Run: npm install -g guarddiff"
  echo "Skipping security check."
  exit 0
fi

echo "Running GuardDiff security check..."
guarddiff staged --fail-on critical
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
  echo ""
  echo "GuardDiff blocked this commit. Fix the issues above before committing."
  echo "To skip: git commit --no-verify"
fi

exit $EXIT_CODE
`;

export function runInitCommand(options: InitCommandOptions): number {
  const cwd = process.cwd();

  writeFileIfAllowed(path.join(cwd, "guarddiff.config.yaml"), DEFAULT_CONFIG, options.force);
  writeFileIfAllowed(path.join(cwd, ".guarddiffignore"), DEFAULT_IGNORE, options.force);
  writeFileIfAllowed(path.join(cwd, ".pre-commit-hooks.yaml"), DEFAULT_PRE_COMMIT_HOOKS, options.force);

  if (options.preCommit) {
    const destination = path.join(cwd, ".git", "hooks", "pre-commit");
    writeFileIfAllowed(destination, DEFAULT_PRE_COMMIT_HOOK, options.force);
    fs.chmodSync(destination, 0o755);
  }

  if (options.githubAction) {
    const destination = path.join(cwd, ".github", "workflows", "guarddiff.yml");
    writeFileIfAllowed(destination, DEFAULT_GITHUB_ACTION, options.force);
  }

  process.stdout.write("GuardDiff init completed.\n");
  return 0;
}

function writeFileIfAllowed(filePath: string, content: string, force = false): void {
  if (fs.existsSync(filePath) && !force) {
    return;
  }

  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, "utf8");
}
